#!/bin/bash
#SBATCH --array=1-16
#SBATCH -N 1 --ntasks-per-node=2 --time=48:00:00
#SBATCH -e qsub.qsh.err -o qsub.qsh.out
#SBATCH -A zimmerman
#SBATCH -p guest --job-name=Al_all_noH

. /etc/profile.d/slurm.sh

ID=`printf "%0*d\n" 3 ${SLURM_ARRAY_TASK_ID}`

cd `pwd`

source /export/zimmerman/paulzim/qchem/qchemjan42013cg/paul.set.local0 
name=`ls q$ID*.inp`
qchem -np 2 $name $name.out




rm $QCSCRATCH
