#!/bin/bash

if [ ! -f all5.xyz ];
then
  echo "all5.xyz file does not exist"
  echo "copy all5.xyz into this folder and try again"
  exit 0
else

NUMLINES=$(grep -c '' all5.xyz) #num lines in all5.xyz
FIRSTLINE=`head -n 1 all5.xyz`  #num atoms in structure
atoms=$((FIRSTLINE+2))          #atoms + 2 = 1 structure
structures=$((NUMLINES/atoms))  #number of structures
echo $atoms
echo $structures


a=0
b=1
c=0
d=1
name='q001'
while [ $a -lt $structures ]
do
   prefix=`printf %03d.%s  $d`
   inpName="q${prefix}structure_$d.inp"
  
   echo $inpName
   b=$[$b+2]
   c=$[$b+$FIRSTLINE]
   echo $b
   echo $c
   tail -n +$b all5.xyz | head -n $(($c-$b)) > tempFile
   #$printline b,c all5.xyz > tempFile
   cat sample.inp charge.inp tempFile end.inp > $inpName
   b=$c
   a=$[$a+1]
   d=$[$d+1]
done
fi

rm -f tempFile
